name: chromatic

on: push

jobs:
  chromatic-deployment:
    name: Deploy Storybook to chromatic
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
        working-directory: wp-content/themes/team31-theme/momo-frontend

      - name: Publish to Chromatic
        run: |
          cd wp-content/themes/team31-theme/momo-frontend
          npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
